### ISSUE TITLE
Not killing the proccess

### ISSUE THREAD

**Issue by NotRandomBruh** [kznamst/DropDownTx#2]
I was wondering if there is a way to not to have to kill the process, keep it running in background or something, i don't want to kill it 'cause i want to maintain the history of what i have done in it, and the output of my commands in my current session. I've tried to play a little with the wmctrl but nothing good has happened.

**Comment by BioBox** [comment]
I got u boi: #3 :grin:

**Comment by chreniuc** [comment]
I forgot about this repository, I haven't used this script for years.. I will merge that pull request as it is.
